# Imagen base de Java 17
FROM openjdk:17-jdk-slim

# Directorio de trabajo en el contenedor
WORKDIR /app

# Copiamos el jar generado al contenedor
COPY target/springboot-diabetico-0.0.1-SNAPSHOT.jar app.jar

# Exponemos el puerto del backend
EXPOSE 5281

# Comando de arranque
ENTRYPOINT ["java", "-jar", "app.jar"]
